name: reviewdog
on: [pull_request]

jobs:
  textlint:
    runs-on: Ubuntu-latest
    container:
      image: node:latest
      env:
        LEVEL: error
        FLAGS: Draft
    steps:
      - uses: actions/checkout@v1
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]

      - name: installl-textlint
        run: |
          cd "$GITHUB_WORKSPACE"
          npm init -y
          npm install -g textlint textlint-filter-rule-allowlist textlint-filter-rule-comments textlint-rule-preset-ja-technical-writing

      - name: run-reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          textlint -f checkstyle "${FLAGS:-'.'}" \
            | reviewdog -f=checkstyle -name="textlint" -diff="git diff ${{ github.event.pull_request.base.ref }}" -reporter=github-pr-review -level="${LEVEL}"
